### ISSUE TITLE
Links in extension popup window can't be opened

### ISSUE THREAD

**Issue by tomayac** [fpmon/fingerprinting-monitor#2]
<img width="345" alt="Screen Shot 2020-12-04 at 16 45 07" src="https://user-images.githubusercontent.com/145676/101183728-2f132700-3650-11eb-9052-15d16786cfe8.png">

**Comment by tomayac** [comment]
For some reason you have minified the code of the extension, so I won't open a proper PR, but the fix is to assign a click listener on the table with the links that opens them in a new tab. Add this to `popup.js`:

```js
document.querySelector('#fingerprint_scripts').addEventListener('click', (e) => {
  if (e.target.nodeName !== 'A') {
    return;
  }
  e.preventDefault();
  chrome.tabs.create({active: true, url: e.target.href});
});
```

**Comment by fpmon** [comment]
Thanks for helping! We will merge this soon. 
Another workaround is to right-click the link and select "Open Link in New Tab".
